package com.insurance.handler;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReceiveTaskHandler implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ReceiveTaskHandler() {
    }




}