package com.insurance.handler;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SendTaskHandler implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SendTaskHandler() {
    }




}